### PR TITLE
explicitly import whoami functions

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
@krlmlr in the default arguments of `create_demo_project()` which is why, I suppose, it wasn't "counted" as import.

https://github.com/cynkra/fledge/blob/e75bc1b46031ee908d8b061bbe79274778baabd0/R/repo-helper.R#L14-L17

**Comment by krlmlr** [comment]
Thanks. I'd prefer `NULL` defaults for these arguments, and using bare `fullname()` and `email_address()` calls in the body. Sending to CRAN after that.

**Review by krlmlr — APPROVED** [review]
Many thanks, I think we're good to launch now!

**Comment by maelle** [comment]
> Many thanks, I think we're good to launch now!

Let me run all checks one last time :wink:

**Pull request merged**
