### PR TITLE
docs: deprecate update_version()

### PR DESCRIPTION
**Pull request by maelle**
How do you usually do deprecations?

And to which branch should I actually make this PR? :thinking:

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
Thanks. This perhaps needs the .svg files in `man/` , happy to use `lifecycle::deprecate_soft()` .

**Comment by krlmlr** [comment]
This branch now has conflicts. I don't mind adding the infrastructure to the main branch first.

**Comment by maelle** [comment]
you mean making all changes from this small PR in a PR to main?

**Comment by krlmlr** [comment]
Done already, I believe.

**Pull request closed without merging**
