### PR TITLE
experiment with less resource wasting

### LINKED ISSUE #135: pkgdown preview
Following https://github.com/cynkra/fledge/pull/128#issuecomment-932496862

* From reading the GHA workflow, using this will overwrite the current dev website? Why not create a Netlify website for PR previews (for internal PRs)? That's what the pkgdown repo itself has.
* At the moment with the desc bug the pkgdown website won't render with the dev version of pkgdown.

### PR DESCRIPTION
**Pull request by maelle**
Fix #135 

@krlmlr I have been thinking about wasting resources cf https://www.ryanfiller.com/blog/why-my-blog-stopped-using-deploy-previews

With this workflow, to get a preview one adds the "needs-preview" label. I'd like to merge this to then try again as currently I think the PR workflow from master applies? I see the label workflow works but I am not sure it posts the URL as commit status.

### CODE REVIEW

**Comment by maelle** [comment]
Ah I think it now really works (the regex in the pkgdown workflow was catching this branch :sweat_smile: )

**Comment by maelle** [comment]
@krlmlr I'm hoping it'd also work for forks.

**Comment by krlmlr** [comment]
Can we deploy automatically, but only if the documentation changes?

We're still running a huge build matrix...

**Comment by maelle** [comment]
> Can we deploy automatically, but only if the documentation changes?

Do you mean pre-pkgdown building or do you mean post-pkgdown building? It's unclear to me where we'd store information on what the last deploy website and source were. :thinking: 

With this change we'd manually decide whether to label the PR as needs-preview so I assume less often than at each commit.

**Comment by krlmlr** [comment]
We'd assume that `gh-pages` contains the last deployed website, and deploy to Netlify only if the current state has changes? Of course this requires stable pkgdown builds, which isn't always given.

Let's put this on the backburner for now.

**Comment by krlmlr** [comment]
The biggest waste is running the big check matrix, I'm mitigating this by only doing this for contributed PRs. Might consider switching to weekly checks (instead of daily) for all packages too.

**Pull request closed without merging**
