### PR TITLE
feat: New internal `release_after_cran_built_binaries()` to support automated CRAN release from GHA

### LINKED ISSUE #648: CRAN watching automation
@krlmlr code that could run every... 4 hours?

``` r
pkg <- "tibble"

temp_file <- withr::local_tempfile()

curl::curl_download(
  sprintf("https://cran.r-project.org/package=%s", pkg),
  temp_file
)

pkg_cran_page <- xml2::read_html(temp_file)
pkg_version_pre <- xml2::xml_find_first(pkg_cran_page, ".//td[text()='Version:']")
pkg_version <- xml2::xml_siblings(pkg_version_pre)[[1]] |>
  xml2::xml_text()

# treat binaries link
tibblify_binary_link <- function(link, os) {
  binary_version <- sub(sprintf("%s_", pkg), "", fs::path_ext_remove(fs::path_file(link)))
  r_version = fs::path_file(fs::path_dir(link))
  
  tibble::tibble(
    binary_version = binary_version,
    r_version = r_version,
    os = os
  )
}

# windows binaries
windows_binaries <- xml2::xml_find_all(
  pkg_cran_page, 
  ".//a[starts-with(@href, '../../../bin/windows/contrib/')]"
) |>
  xml2::xml_attr("href") |>
  purrr::map_df(tibblify_binary_link, os = "windows")

# macOS binaries
mac_binaries <- xml2::xml_find_all(
  pkg_cran_page, 
  ".//a[starts-with(@href, '../../../bin/macosx/')]"
) |>
  xml2::xml_attr("href") |>
  purrr::map_df(tibblify_binary_link, os = "mac") 

# put it together
binaries <- rbind(windows_binaries, mac_binaries)
binaries[["up_to_date"]] <- binaries[["binary_version"]] == pkg_version

all_ok <- all(binaries[["up_to_date"]])

binaries
#> # A tibble: 7 × 4
#>   binary_version r_version os      up_to_date
#>   <chr>          <chr>     <chr>   <lgl>     
#> 1 3.2.0          4.3       windows TRUE      
#> 2 3.1.8          4.2       windows FALSE     
#> 3 3.1.8          4.1       windows FALSE     
#> 4 3.2.0          4.2       mac     TRUE      
#> 5 3.2.0          4.1       mac     TRUE      
#> 6 3.1.8          4.2       mac     FALSE     
#> 7 3.1.8          4.1       mac     FALSE
all_ok
#> [1] FALSE
```

<sup>Created on 2023-03-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by maelle**
Fix #648 

Is this where this code should live?

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. Here is good for now, I'll move it from here to `fledge.yaml` and distribute from there via actions-sync.

**Comment by krlmlr** [comment]
Thanks! I had to tweak a bit, will do a few more local tests.

**Comment by krlmlr** [comment]
https://github.com/cynkra/dm/actions/runs/4440862891

Works like a charm, thanks!

**Comment by krlmlr** [comment]
Due to the branch name, we're checking all dev versions with every push 🤪

**Comment by maelle** [comment]
> Due to the branch name, we're checking all dev versions with every push :zany_face:

How so?

**Comment by krlmlr** [comment]
`cran-` prefix.

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
