### PR TITLE
ci: add test prefix to snapshot updates PR template

### PR DESCRIPTION
**Pull request by maelle**
I'd like to also get rid of `(null)` but not sure where

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. I believe these PRs should never ever end up in NEWS.md . Do we have a prefix for that?

**Comment by maelle** [comment]
No but that would go in #339

**Comment by krlmlr** [comment]
GHA complains about the syntax -- should we use a separator different from `:` ?

**Comment by maelle** [comment]
> GHA complains about the syntax -- should we use a separator different from : ?

Oops, it makes sense with YAML, sorry about that. I added quotes.

**Comment by krlmlr** [comment]
This now has conflicts too, sorry about that.

**Comment by krlmlr** [comment]
Unrelated, but why is the fledge workflow even run here?

**Comment by maelle** [comment]
I opened #597

Are further changes needed in this PR?

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
