### PR TITLE
Remove false Markdown link?

### PR DESCRIPTION
**Pull request by maelle**
Where is the styling bot name defined?

### CODE REVIEW

**Comment by krlmlr** [comment]
Should we go with a regex, e.g., ignore users that match `^[0-9]+-github-actions` ?

**Comment by maelle** [comment]
Do you mean we have no control over that username, is it defined by GitHub Actions? The problem with it is that it makes parsing wrong as it's not supposed to be a link.

**Comment by krlmlr** [comment]
I'm not sure where that username comes from, and I think we don't need to credit it in `NEWS.md` . Can we avoid mentioning it at all?

**Comment by maelle** [comment]
Before adding complexity to fledge I'd like to be sure where this username comes from. Where should I read more about the styling workflow?

**Comment by krlmlr** [comment]
Thanks. Let's watch out for more instances of this problem to pinpoint the exact conditions when it occurs. This looks like a rabbit hole I'm not ready to enter today.

**Pull request merged**
