### PR TITLE
Add {galley} test structure

### PR DESCRIPTION
**Pull request by pat-s**
Not functional yet because the temporary paths change on every run and let the comparison fail.

Feel free to use this PR as a starting point.

### CODE REVIEW

**Comment by krlmlr** [comment]
Can you please integrate with #70?

**Comment by pat-s** [comment]
- In `git init -b main` the `-b` flag requires `git >= 2.28`. rmarkdown by default does not honor user profiles and therefore defaults to the system git installation (on macOS `/usr/bin/git`) which is only 2.24. To honor user profiles and include custom PATH entries, I added chunk option `engine.opts='-l'`.
- A fixed temporary path is needed to get tests passing, otherwise the tempdir paths will fluctuate in every new session.
- {galley} is still private, hence dep installation fails. Locally tests are passing for me.

`devtools::test()` is working but R CMD Check is still causing troubles related to dirs. Do you have a solutions for this? Maybe similar to what is done in {here}?

**Comment by krlmlr** [comment]
Thanks for working on this.

- Do we need to run in a vanilla R session via `r_vanilla()`?
- `tempdir()` fluctuations should be handled by galley? We should fix there so that the vignette works unchanged.
- We need to open-source or inline galley so that tests pass.
- Let's deal with `R CMD check` when the checks work here.

**Comment by pat-s** [comment]
AFAICS you went with a backed-in solution for atomic vignette tests.
Can this PR be closed?

Do you still want to make {galley} public at all or do you favour the current approach?

**Comment by krlmlr** [comment]
Thanks. I like the current approach of explicit snapshot tests. At some point I think galley will make it easier to create and maintain those tests, but it won't be necessary to run the tests.

**Pull request closed without merging**
